# Generated by Django 3.1.3 on 2020-11-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('base_url', models.CharField(max_length=200, verbose_name='URLBase')),
                ('date', models.CharField(max_length=50, verbose_name='Date')),
                ('relevance', models.CharField(max_length=50, verbose_name='Relevance')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('email', models.CharField(max_length=80, verbose_name='Email')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
            ],
        ),
    ]
